version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd user/backend && npm install --omit=dev && cd ../..
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - node --version
      - npm --version
  
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Copying backend files to deployment directory..."
      - mkdir -p deploy
      - cp -r user/backend/* deploy/
      - cp -r user/backend/.ebextensions deploy/ 2>/dev/null || true
      - cp -r user/backend/.platform deploy/ 2>/dev/null || true
      - ls -la deploy/
  
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Deployment package ready"
      - ls -la deploy/

artifacts:
  base-directory: deploy
  files:
    - '**/*'

cache:
  paths:
    - 'user/backend/node_modules/**/*'
